// @generated by Cratis. Source: Core.Identity.IdentityDetails. Time: 2026-06-25T20:11:34.5490650Z. Hash: 64FD506023B7C7C2FE21186FC2A991D4BE564489E5652AECFD5A1A1F559286A7
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class IdentityDetails {
    @field(String)
    userId!: string;
    @field(String)
    name!: string;
    @field(String)
    email!: string;
}
