// @generated by Cratis. Source: Library.Employment.Employees.Hire.HireEmployee. Time: 2026-06-25T18:16:30.0918720Z. Hash: 021B38DEFC65AD5191E057BCF63628BA104F82668C8995FA2599C62710D3E17F
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IHireEmployee {
    department?: string;
    name?: string;
}

export class HireEmployeeValidator extends CommandValidator<IHireEmployee> {
    constructor() {
        super();
    }
}

export class HireEmployee extends Command<IHireEmployee, Guid> implements IHireEmployee {
    readonly route: string = '/api/employment/employees/hire';
    readonly validation: CommandValidator = new HireEmployeeValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('department', String, false),
        new PropertyDescriptor('name', String, false),
    ];

    private _department!: string;
    private _name!: string;

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get department(): string {
        return this._department;
    }

    set department(value: string) {
        this._department = value;
        this.propertyChanged('department');
    }
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }

    static use(initialValues?: IHireEmployee): [HireEmployee, SetCommandValues<IHireEmployee>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<HireEmployee, IHireEmployee>(HireEmployee, initialValues);
    }
}
