// @generated by Cratis. Source: Library.Employment.Employees.Listing.Employee. Time: 2026-06-25T18:16:30.1292640Z. Hash: 6A4B1110CB393FD69D93575D75BFCF31CE9051E667D6E06D9B4C049F418DA960
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { Guid } from '@cratis/fundamentals';

export class Employee {
    @field(Guid)
    id!: Guid;
    @field(String)
    name!: string;
    @field(String)
    department!: string;
}
