// @generated by Cratis. Source: Core.Employment.Employees.Listing.Employee. Time: 2026-06-25T18:19:56.2594990Z. Hash: 6DB1DFF50ADB863F10136B108B9099D1590DCF96A209432028D15A3CB19A95AC
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Employee } from './Employee';

class ObserveAllSortBy {

    constructor(readonly query: ObserveAll) {
    }

}

class ObserveAllSortByWithoutQuery {

}

export class ObserveAll extends ObservableQueryFor<Employee[]> {
    readonly route: string = '/api/employment/employees/listing/observe-all';
    readonly queryName: string = 'Core.Employment.Employees.Listing.Employee.ObserveAll';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Employee[] = [];
    private readonly _sortBy: ObserveAllSortBy;
    private static readonly _sortBy: ObserveAllSortByWithoutQuery = new ObserveAllSortByWithoutQuery();

    constructor() {
        super(Employee, true);
        this._sortBy = new ObserveAllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): ObserveAllSortBy {
        return this._sortBy;
    }

    static get sortBy(): ObserveAllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Employee[]>, SetSorting] {
        return useObservableQuery<Employee[], ObserveAll>(ObserveAll, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Employee[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Employee[], ObserveAll>(ObserveAll, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Employee[]>, SetSorting] {
        return useSuspenseObservableQuery<Employee[], ObserveAll>(ObserveAll, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Employee[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Employee[], ObserveAll>(ObserveAll, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Employee) => unknown, sorting?: Sorting): ChangeSet<Employee> {
        return useChangeStream<Employee, ObserveAll>(ObserveAll, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ObserveAll, Employee[]> {
        return new ObservableQueryWhen<ObserveAll, Employee[]>(ObserveAll, condition);
    }
}
